dh_values:
    link1:
        r: 0.0
        d: 0.118016
        alpha: 1.5707
        theta: 0.0

    link2:
        r: -0.63
        d: 0.0
        alpha: 0.0
        theta: 0.0

    link3:
        r: -0.645675
        d: 0.0
        alpha: 0.0
        theta: 0.0

    link4:
        r: 0
        d: 0.08505
        alpha: 1.5707
        theta: 0

    link5:
        r: 0
        d: 0.044
        alpha: -1.5707
        theta: 0

home_position: [0, -1.5707, 1.5707, 1.5707, 0]

joint_limits:
    # 360 degrees
    joint1:
        min: -3.1415
        max: 3.1415

    # 105 degrees
    joint2:
        min: -2.0944
        max: 0.2618

    # 120 degrees
    # joint3:
    #     min: -1.5708
    #     max: 0.5236
    joint3:
        min: 0.1745
        max: 2.967

    # 360 degrees sweep
    # joint4:
    #     min: -3.1415
    #     max: 3.1415
    joint4:
        min: 0.3491
        max: 3.1415

    # 360 degrees sweep
    joint5:
        min: -3.1415
        max: 3.1415



