- link1:
    r: 0.0
    d: 0.15185
    alpha: 1.570796327
    theta: 0.0
    min_joint_limit: 0.0
    max_joint_limit: 6.283185307

- link2:
    r: -0.24355
    d: 0.0
    alpha: 0.0
    theta: 0.0
    min_joint_limit: 0.0
    max_joint_limit: 6.283185307

- link3:
    r: -0.2132
    d: 0.0
    alpha: 0.0
    theta: 0.0
    min_joint_limit: 0.0
    max_joint_limit: 6.283185307

- link4:
    r: 0.0
    d: 0.13105
    alpha: 1.570796327
    theta: 0.0
    min_joint_limit: 0.0
    max_joint_limit: 6.283185307

- link5:
    r: 0.0
    d: 0.08535
    alpha: -1.570796327
    theta: 0.0
    min_joint_limit: 0.0
    max_joint_limit: 6.283185307

- link6:
    r: 0.0
    d: 0.0921
    alpha: 0.0
    theta: 0.0
    min_joint_limit: 0.0
    max_joint_limit: 6.283185307

